# Generated by Django 5.2.17 on 2026-09-30 09:46

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='file')),
                ('file_size', models.IntegerField()),
                ('mime_type', models.CharField(max_length=200)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('PROCESSING', 'processing'), ('READY', 'ready'), ('FAILED', 'failed')], default='PROCESSING')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['title'], name='document_do_title_a4a8bf_idx'), models.Index(fields=['uploaded'], name='document_do_uploade_dcd14d_idx')],
            },
        ),
    ]
