# Generated by Django 5.2.17 on 2026-10-02 13:14

import datetime
import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nightly_brain', '0002_voicebriefing'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicebriefing',
            name='embeddings',
            field=pgvector.django.vector.VectorField(default=datetime.datetime(2026, 10, 2, 13, 14, 31, 582643, tzinfo=datetime.timezone.utc), dimensions=1024),
            preserve_default=False,
        ),
    ]
