# Generated by Django 5.2.17 on 2026-10-02 13:15

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nightly_brain', '0003_voicebriefing_embeddings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicebriefing',
            name='embeddings',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
        ),
    ]
